version: '3.8'

services:
  db:
    image: postgres:15
    container_name: cse_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: cse_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db


  spark-master:
    image: apache/spark:latest
    container_name: cse_spark_master
    user: root
    command: >
      bash -c "pip install numpy python-dotenv && 
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master"
    ports:
      - "8080:8080"  # Spark Master Web UI
      - "7077:7077"  # Spark Master Port
    volumes:
      - .:/app
    working_dir: /app

  spark-worker:
    image: apache/spark:latest
    container_name: cse_spark_worker
    user: root
    command: >
      bash -c "pip install numpy python-dotenv && 
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"depends_on:
      - spark-master
    volumes:
      - .:/app
    working_dir: /app

  # ingestor:
  #   build: .
  #   container_name: cse_ingestor
  #   depends_on:
  #     - db
  #   environment:
  #     - DATABASE_URL=${LOCAL_DATABASE_URL}
  #   volumes:
  #     - .:/app
  #   command: python -m src.ingestion.extractor


  sync:
    build: .
    container_name: cse_sync
    depends_on:
      - db
    environment:
      - LOCAL_DATABASE_URL=${LOCAL_DATABASE_URL}
      - CLOUD_DATABASE_URL=${CLOUD_DATABASE_URL}
    volumes:
      - .:/app
    # command: python -m src.sync.sync_cloud_to_local
    command: bash run_pipeline.sh

volumes:
  postgres_data: